services:
  - docker

git:
  depth: 1

notifications:
  email: false

script:
- ./build.sh
- SRC_CONTAINER="debian" SRC_TAG="stretch-slim" PREFIX="debian-" ./build.sh

deploy:
  on:
    branch: release
  provider: script
  script: ./travis-deploy.sh