#!/bin/bash

# script that correctly interfaces with buildah inside the buildahbox container
DIR=$(pwd)
TARGET_DIR="/var/lib/containers"
IMAGE_TAG="chrisruffalo/buildahbox:latest"
RUNTIME_DIR=${XDG_RUNTIME_DIR:-"/var/run/users/${UID}"}
CONTAINERS_DIR="${RUNTIME_DIR}/buildahbox/containers"

# make containers dir
[[ -d $CONTAINERS_DIR ]] || mkdir -p $CONTAINERS_DIR

DOCKER_OPTIONS="run -ti --privileged -v $DIR:/working -v $RUNTIME_DIR:$RUNTIME_DIR -v $CONTAINERS_DIR:$TARGET_DIR $IMAGE_TAG"

# special command handling for mount option
if [[ $@ == "mount"* ]]; then
	# use sed to replace target directory with external-reachable containers dir
	docker $DOCKER_OPTIONS $@ | sed "s|$TARGET_DIR|$CONTAINERS_DIR|"
else
	# execute command with no special handling
	docker $DOCKER_OPTIONS $@
fi