#!/bin/bash

# script that correctly interfaces with podman inside the buildahbox container
DIR=$(pwd)
PODMAN_BIN="/usr/bin/podman"
PODMAN_DIR="${XDG_RUNTIME_DIR:-"/run/user/${UID}"}/containers/auth.json"
CONTAINERS_DIR="$DIR/.containers"
TARGET_DIR="/var/lib/containers"
IMAGE_TAG="chrisruffalo/buildahbox:latest"

# make containers dir
[[ -d $CONTAINERS_DIR ]] || mkdir -p $CONTAINERS_DIR

# execute command
docker run -ti --privileged --entrypoint "${PODMAN_BIN}" -v $DIR:/working -v $CONTAINERS_DIR:$TARGET_DIR -v $PODMAN_DIR:$PODMAN_DIR $IMAGE_TAG $@
